kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: cds-2025-demo
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 80
    hostPort: 8080
    protocol: TCP
  - containerPort: 443
    hostPort: 6443
    protocol: TCP
