apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: demo-secret-store
  namespace: eso
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: kubernetes
          role: demo
          serviceAccountRef:
            name: demo-serviceaccount
      server: http://vault.demo.svc.cluster.local:8200
      version: v2
